### PR TITLE
Janet Martin - Portfolio 2.0

### PR DESCRIPTION
**Pull request by akamimartin**
Hello,.please review my portfolio - 2.0 when you have time.  Thank you    It still have a ways to go, but I do like the look and feel of the website.  (Also,  the good news, my css file is under 300 lines.  - better than Mboutique css file. :)  

Janet

### CODE REVIEW

**Comment by dpaschal-lf** [comment]
#home
- Your top circle links kind of jump around when you hover over them:
   - screen shot 2015-04-28 at 12 22 39 am
   - screen shot 2015-04-28 at 12 22 45 am
- Might also want to reduce that top space between your name and the top nav a bit too, so more of your circles are visible and it is more obvious that you have more content below them
- might want to put the circle image nav into a container for ease of positioning / reuse independent of other things
#about
- the sidebar is less of sidebar and more of an "article".  Maybe use the <article> element
- the main_content is less main_content, and more of an accompanying image.  Perhaps <figure> or <aside> instead?
- maybe a hover effect on the image in front of the gazebo, with some sort of caption?
#skills
- Definitely want to do more work on the skill list to present the information in a more interesting way, though this is only a first pass, I am sure.
- Put the link to the resume file in a more friendly link.  Also you may want to add target="_blank" to make it open in a new tab/window so they don't leave your page.
- nice Lorem Ipsum factoid!
#contact
- May want to stylize the contact form more to your page's look
- also really will want to center that, and probably make it more horizontal than vertical

**Comment by akamimartin** [comment]
Hi Daniel,
Thank you for the very (excellent detailed review - will work on incorporating them into the website.
Thank you,  
Janet

**Comment by dpaschal-lf** [comment]
I updated my comment to fix some words that were disappearing because I was using 'less than' and 'greater than' symbols to show elements.  Some lines might make more sense now.

**Comment by akamimartin** [comment]
Thank you. -- that does help. Shows me directly what you are refering to :)

**Pull request closed without merging**
